mqtt:
  sensor:
  - name: "Tyre 1 Pressure"
    state_topic: "RTL315/d56e4521"
    icon: mdi:tire
    unit_of_measurement: "psi"
    value_template: "{{ value_json.pressure_PSI }}"
    unique_id: "tpms_Car1_Tyre1_psi"
    device_class: pressure
    
  - name: "Tyre 2 Pressure"
    state_topic: "RTL315/d56e4183"
    icon: mdi:tire
    unit_of_measurement: "psi"
    value_template: "{{ value_json.pressure_PSI }}"
    unique_id: "tpms_Car1_Tyre2_psi"
    device_class: pressure
    
  - name: "Tyre 3 Pressure"
    state_topic: "RTL315/d56e41d8"
    icon: mdi:tire
    unit_of_measurement: "psi"
    value_template: "{{ value_json.pressure_PSI }}"
    unique_id: "tpms_Car1_Tyre3_psi"
    device_class: pressure
    
  - name: "Tyre 4 Pressure"
    state_topic: "RTL315/d56e4484"
    icon: mdi:tire
    unit_of_measurement: "psi"
    value_template: "{{ value_json.pressure_PSI }}"
    unique_id: "tpms_Car1_Tyre4_psi"
    device_class: pressure
    
  - name: "Tyre 1 Temperature"
    state_topic: "RTL315/d56e4521"
    icon: mdi:tire
    unit_of_measurement: "째C"
    value_template: "{{ value_json.temperature_C }}"
    unique_id: "tpms_Car1_Tyre1_temp"
    device_class: temperature
    
  - name: "Tyre 2 Temperature"
    state_topic: "RTL315/d56e4183"
    icon: mdi:tire
    unit_of_measurement: "째C"
    value_template: "{{ value_json.temperature_C }}"
    unique_id: "tpms_Car1_Tyre2_temp"
    device_class: temperature
    
  - name: "Tyre 3 Temperature"
    state_topic: "RTL315/d56e41d8"
    icon: mdi:tire
    unit_of_measurement: "째C"
    value_template: "{{ value_json.temperature_C }}"
    unique_id: "tpms_Car1_Tyre3_temp"
    device_class: temperature
    
  - name: "Tyre 4 Temperature"
    state_topic: "RTL315/d56e4484"
    icon: mdi:tire
    unit_of_measurement: "째C"
    value_template: "{{ value_json.temperature_C }}"
    unique_id: "tpms_Car1_Tyre4_temp"
    device_class: temperature
